### ISSUE TITLE
Mapping to java.lang.Map

### ISSUE THREAD

**Issue by divyakumarjain** [orika-mapper/orika#102]
I am trying to map my Java POJO to java.lang.Map but i am getting error similar to one discussed in link.

https://code.google.com/p/orika/issues/detail?id=146

Full stack trace which i am getting.

```
ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceClass = class de.hybris.platform.commercefacades.order.data.OrderData
destinationType = java.util.Map<Object, Object>
Error occurred: com.thoughtworks.paranamer.ParameterNamesNotFoundException: One or more @Named annotations missing for class 'java.util.LinkedHashMap', methodOrCtor <init> and parameter types int,float,boolean

-----begin dump of current state-----------------------------
Registered object factories: 0 (approximate size: 0.1 kB)
-------------------------------------------------------------
Registered mappers: 0 (approximate size: 0.4 kB)
-------------------------------------------------------------
Registered concrete types: 5 (approximate size: 114.1 kB)
  [interface java.util.List] : ArrayList<Object>
  [interface java.util.Map$Entry] : MapEntry<Object, Object>
  [interface java.util.Map] : LinkedHashMap<Object, Object>
  [interface java.util.Set] : LinkedHashSet<Object>
  [interface java.util.Collection] : ArrayList<Object>
-------------------------------------------------------------
Resolved strategies: 0 (approximate size: 73.9 kB)
-------------------------------------------------------------
Unenhance strategy: ma.glasnost.orika.unenhance.BaseUnenhancer@48ea2003
-----end dump of current state-------------------------------
    at ma.glasnost.orika.impl.ExceptionUtility.newMappingException(ExceptionUtility.java:55)
    at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:273)
    at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:243)
    at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:555)
    at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:1034)
    at ma.glasnost.orika.impl.ConfigurableMapper.mapAsCollection(ConfigurableMapper.java:282)
    at de.hybris.platform.commercewebservicescommons.mapping.impl.DefaultDataMapper.mapAsCollection(DefaultDataMapper.java:234)
    at org.abc.controllers.TypeServiceController.getTypes(TypeServiceController.java:41)
    at org.abc.controllers.TypeServiceControllerTest.getTypes(TypeServiceControllerTest.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.thoughtworks.paranamer.ParameterNamesNotFoundException: One or more @Named annotations missing for class 'java.util.LinkedHashMap', methodOrCtor <init> and parameter types int,float,boolean
    at com.thoughtworks.paranamer.AnnotationParanamer.lookupParameterNames(AnnotationParanamer.java:129)
    at com.thoughtworks.paranamer.AdaptiveParanamer.lookupParameterNames(AdaptiveParanamer.java:75)
    at com.thoughtworks.paranamer.CachingParanamer.lookupParameterNames(CachingParanamer.java:79)
    at com.thoughtworks.paranamer.CachingParanamer.lookupParameterNames(CachingParanamer.java:72)
    at ma.glasnost.orika.constructor.ConstructorParameterResolver.getProperties(ConstructorParameterResolver.java:63)
    at ma.glasnost.orika.constructor.ConstructorParameterResolver.getPossibleConstructorParams(ConstructorParameterResolver.java:119)
    at ma.glasnost.orika.property.PropertyResolver.resolveConstructorProperty(PropertyResolver.java:701)
    at ma.glasnost.orika.property.PropertyResolver.getProperty(PropertyResolver.java:686)
    at ma.glasnost.orika.property.PropertyResolver.getProperty(PropertyResolver.java:616)
    at ma.glasnost.orika.metadata.ClassMapBuilder.resolveProperty(ClassMapBuilder.java:828)
    at ma.glasnost.orika.metadata.ClassMapBuilderForMaps.resolveProperty(ClassMapBuilderForMaps.java:176)
    at ma.glasnost.orika.metadata.FieldMapBuilder.<init>(FieldMapBuilder.java:78)
    at ma.glasnost.orika.metadata.FieldMapBuilder.<init>(FieldMapBuilder.java:61)
    at ma.glasnost.orika.metadata.ClassMapBuilder.fieldMap(ClassMapBuilder.java:309)
    at ma.glasnost.orika.metadata.ClassMapBuilderForMaps.fieldMap(ClassMapBuilderForMaps.java:157)
    at ma.glasnost.orika.metadata.ClassMapBuilderForMaps.byDefault(ClassMapBuilderForMaps.java:129)
    at ma.glasnost.orika.metadata.ClassMapBuilderForMaps.byDefault(ClassMapBuilderForMaps.java:38)
    at ma.glasnost.orika.metadata.ClassMapBuilder.byDefault(ClassMapBuilder.java:559)
    at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:750)
    at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:707)
    at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:584)
    at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:216)
    at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:261)
    ... 34 more
```

**Comment by andreabertagnolli** [comment]
Can you report a failing test case? I tried with the one present in the link but it works
