### ISSUE TITLE
RamUsageEstimator fails with ClassNotFound

### ISSUE THREAD

**Issue by leonard84** [orika-mapper/orika#106]
As the title already says the `RamUsageEstimator` fails with `ClassNotFound` when inspecting the `objectFactoryRegistry` (see Stacktrace below). This in turn hides the real Exception in the mapping. State reporting should not fail with exceptions caused by it or its underlying tools. I guess this has to do with something funny with the classloader.

There is already a property for `DUMP_STATE_ON_EXCEPTION` maybe another one would make sense `INCLUDE_SIZE_IN_STATE_DUMP`, which would control the inclusion of the `RamUsageEstimator`.

```
java.lang.ClassNotFoundException: com.private.Representation
      at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_66]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_66]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_66]
      at java.lang.Class.getDeclaredFields0(Native Method) ~[na:1.8.0_66]
      at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[na:1.8.0_66]
      at java.lang.Class.getDeclaredFields(Class.java:1916) ~[na:1.8.0_66]
      at com.carrotsearch.sizeof.RamUsageEstimator.createCacheEntry(RamUsageEstimator.java:568) ~[java-sizeof-0.0.4.jar:na]
      at com.carrotsearch.sizeof.RamUsageEstimator.measureSizeOf(RamUsageEstimator.java:532) ~[java-sizeof-0.0.4.jar:na]
      at com.carrotsearch.sizeof.RamUsageEstimator.sizeOfAll(RamUsageEstimator.java:380) ~[java-sizeof-0.0.4.jar:na]
      at com.carrotsearch.sizeof.RamUsageEstimator.sizeOfAll(RamUsageEstimator.java:361) ~[java-sizeof-0.0.4.jar:na]
      at ma.glasnost.orika.StateReporter.humanReadableSizeInMemory(StateReporter.java:48) ~[orika-core-1.4.6.jar:na]
      at ma.glasnost.orika.impl.DefaultMapperFactory.reportCurrentState(DefaultMapperFactory.java:1559) ~[orika-core-1.4.6.jar:na]
      at ma.glasnost.orika.StateReporter.reportCurrentState(StateReporter.java:33) ~[orika-core-1.4.6.jar:na]
      at ma.glasnost.orika.impl.ExceptionUtility.decorate(ExceptionUtility.java:65) ~[orika-core-1.4.6.jar:na]
      at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:209) ~[orika-core-1.4.6.jar:na]
      at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:741) ~[orika-core-1.4.6.jar:na]
      at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:721) ~[orika-core-1.4.6.jar:na]
      at ma.glasnost.orika.impl.ConfigurableMapper.map(ConfigurableMapper.java:150) ~[orika-core-1.4.6.jar:na]
...
```

Another weird thing I noticed when logging all classes the RamUsageEstimator looks at, is that it looks at way too many classes in `com.carrotsearch.sizeof.RamUsageEstimator#createCacheEntry` which should not be part of the mapping.

**Comment by elaatifi** [comment]
This should be disabled by default, should be enabled only for troubleshooting (as it impacts also the performance)

But I agree with you on the exception part.

**Comment by leonard84** [comment]
`valueOf(getProperty(DUMP_STATE_ON_EXCEPTION, "true"))`  is enabled by default at the moment

**Comment by elaatifi** [comment]
Yes and actually is another issue (in addition to the issue you raised) !

**Comment by novtor** [comment]
Having similar issue:
java.lang.ClassNotFoundException: javax.transaction.TransactionManager
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2387)
        at java.lang.Class.getDeclaredFields(Class.java:1796)
        at com.carrotsearch.sizeof.RamUsageEstimator.createCacheEntry(RamUsageEstimator.java:568)
        at com.carrotsearch.sizeof.RamUsageEstimator.measureSizeOf(RamUsageEstimator.java:532)
        at com.carrotsearch.sizeof.RamUsageEstimator.sizeOfAll(RamUsageEstimator.java:380)
        at com.carrotsearch.sizeof.RamUsageEstimator.sizeOfAll(RamUsageEstimator.java:361)
        at ma.glasnost.orika.StateReporter.humanReadableSizeInMemory(StateReporter.java:48)

**Comment by andreabertagnolli** [comment]
There's a way to replicate this exception?

**Comment by elaatifi** [comment]
I think the best thing todo is to disabled it by default.
valueOf(getProperty(DUMP_STATE_ON_EXCEPTION, "true")), default value should be "false"

**Comment by andreabertagnolli** [comment]
I did the pull request, I think now this issue can be close until a way to replicate it.

**Comment by markthegrea** [comment]
This is still happening in our production environment and nowhere else.

java.lang.ClassNotFoundException: javax.transaction.TransactionManager

Is this a mapping problem or is the changine the setting above a "fix"?

**Comment by elaatifi** [comment]
This happen only when there is already an exception even for previous release. But has been disabled by default in 1.5.

You can also disabled for previous release by adding -Dma.glasnost.orika.dumpStateOnException=false to JVM parameters
