### ISSUE TITLE
How to map CurrencyUnit field

### ISSUE THREAD

**Issue by ptahchiev** [orika-mapper/orika#128]
Hello,

I have an object that holds a reference to JavaMoney's `CurrencyUnit` :

````
public class MyObject {

     private CurrencyUnit currency;

}
````

Now when I try to map this object I get the following exception:

````
Caused by: java.lang.IllegalStateException: Cannot create a mapper for classes : JDKCurrencyAdapter, JDKCurrencyAdapter
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:591)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:212)
	at ma.glasnost.orika.impl.DefaultBoundMapperFacade$BoundStrategyCache.getStrategy(DefaultBoundMapperFacade.java:259)
	at ma.glasnost.orika.impl.DefaultBoundMapperFacade.map(DefaultBoundMapperFacade.java:137)
	at ma.glasnost.orika.generated.Orika_PriceEntity_PriceEntity_Mapper2366592654834$1.mapAtoB(Orika_PriceEntity_PriceEntity_Mapper2366592654834$1.java)
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:67)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:740)

````

I think it is because the `JDKCurrencyAdapter` does not have a default constructor, so I tried to register an object factory:

````
factory.registerObjectFactory(new CurrencyFactory(), TypeFactory.valueOf(JDKCurrencyAdapter.class));
````

and as you can see my object factory is registered:
````
  [JDKCurrencyAdapter] : {Object=com.nemesis.platform.core.factory.CurrencyFactory@611e4e76}
````

but it is never called.

**Comment by ptahchiev** [comment]
Ignore my question. I actually managed to do it, by specifying a pass-through converter for `CurrencyUnit`:

````
        factory.getConverterFactory().registerConverter(new PassThroughConverter(CurrencyUnit.class));
````
