### ISSUE TITLE
Unable to map derived class

### ISSUE THREAD

**Issue by udalrich** [orika-mapper/orika#177]
I have the following data structure

    class Container {
        public Thing getThing();
    }

which I want to map to this structure:

    class ContainerOut {
         public setThing(BaseThing);
    }
    class BaseThing {}
    class MidThing extends BaseThing {}
    class DerivedThing extends MidThing {}

I have a mapping from `Container` to `ContainerOut` and mapping from `Thing` to `DerivedThing`.  Turning on debugging shows that the mappings from `Container` to `ContainerOut` and `Thing` to `DerivedThing` are present, and the `Container` `mapAtoB` info includes

> 	 Field(target(Thing), taskingSubject(BaseThing)) : mapping object to object

However, the attempt to map the `Container` fails with

> java.lang.IllegalStateException: Cannot create a mapper for classes : BaseThing, Thing
>	at ma.glasnost.orika.impl.ExceptionUtility.newMappingException(ExceptionUtility.java:55) ~[cdrMediator-0.0.1-SNAPSHOT-withDependencies.jar:na]
>	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:280) ~[cdrMediator-0.0.1-SNAPSHOT-withDependencies.jar:na]
>	at ma.glasnost.orika.impl.MapperFacadeImpl.mapElement(MapperFacadeImpl.java:868) ~[cdrMediator-0.0.1-SNAPSHOT-withDependencies.jar:na]
>	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:693) ~[cdrMediator-0.0.1-SNAPSHOT-withDependencies.jar:na]
>	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsList(MapperFacadeImpl.java:446) ~[cdrMediator-0.0.1-SNAPSHOT-withDependencies.jar:na]

 Looking at my actual data structure, it appears that I am actually mapping a class that has a list of `Container` objects.

I am using orika-core 1.4.6 from github.

I have also implemented a custom resolver strategy, which does two things.  `isAcceptable` checks that the class is in the same package as `Container`, and `shouldPreferClassOverInterface` returns false.  Both of these are the correct action when mapping from `ContainerOut` to `Container`.  `isAcceptable` also does not appear to ever be called with a class from the `ContainerOut` heirarchy, so I am not sure that it is being applied in the problem conversion.

**Comment by udalrich** [comment]
It looks like this was fixed when I upgraded to 1.5.0.
