### ISSUE TITLE
Wrong code generated for map to object mapping

### ISSUE THREAD

**Issue by foal** [orika-mapper/orika#181]
I have the DTO and model

DTO has field `private final Map<Long, Double> stylistBreakdown = new HashMap<>();`
Model - 	private `List<StylistBreakdown> stylistBreakdown = ImmutableList.of();`
StylistBreakdown contains two fields:
```Java
	private UserModel stylist;
	private double value;
```
Registered custom mapper
```Java
		return factory
				.classMap(CashReportDto.class, CashReportModel.class)
				.field("stylistBreakdown{key}", "stylistBreakdown{stylist}")
				.field("stylistBreakdown{value}", "stylistBreakdown{value}")
				.byDefault();
```
Code generated for mapper contains the error on double conversion `((double)stylistBreakdown_destination0Element.getValue()) == ((java.lang.Double)stylistBreakdown_source0Element.getValue()).java.lang.DoubleValue())))`

Fill error report is:
```
20:32:38.474 [localhost-startStop-1] ERROR m.g.o.i.g.JavassistCompilerStrategy - An exception occured while compiling the following method:

 	public void mapAtoB(java.lang.Object a, java.lang.Object b, ma.glasnost.orika.MappingContext mappingContext) {


super.mapAtoB(a, b, mappingContext);


// sourceType: CashReportDto
com.jresearchsoft.booking.ft.common.pos.manager.api.dto.CashReportDto source = ((com.jresearchsoft.booking.ft.common.pos.manager.api.dto.CashReportDto)a); 
// destinationType: CashReportModel
com.jresearchsoft.booking.ft.admin.module.shared.pos.model.CashReportModel destination = ((com.jresearchsoft.booking.ft.admin.module.shared.pos.model.CashReportModel)b); 


destination.setBalanceRepoted(((double)source.getBalanceRepoted())); 
destination.setBankDeposit(((double)source.getBankDeposit())); 
destination.setBreakdownChildren(((double)source.getBreakdownChildren())); 
destination.setBreakdownLadies(((double)source.getBreakdownLadies())); 
destination.setBreakdownMen(((double)source.getBreakdownMen())); 
destination.setBreakdownProducts(((double)source.getBreakdownProducts())); 
destination.setCancelationAmount(java.lang.Integer.valueOf(""+((ma.glasnost.orika.Converter)usedConverters[0]).convert(java.lang.Double.valueOf(((double)source.getCancelationAmount())), ((ma.glasnost.orika.metadata.Type)usedTypes[0]), mappingContext)).intValue()); 
destination.setCashDifference(((double)source.getCashDifference())); 
destination.setCashVoucherRate(((double)source.getCashVoucherRate())); 
destination.setCurrency(((java.lang.String)source.getCurrency())); 
if ( !(((org.joda.time.DateTime)source.getDate()) == null)){ 
destination.setDate(((org.jresearch.commons.gwt.shared.model.time.GwtDateTimeModel)((ma.glasnost.orika.Converter)usedConverters[1]).convert(((org.joda.time.DateTime)source.getDate()), ((ma.glasnost.orika.metadata.Type)usedTypes[1]), mappingContext))); 
} else { 
destination.setDate(null);
 }
destination.setDeposit(((double)source.getDeposit())); 
destination.setDiscounts(((double)source.getDiscounts())); 
destination.setExpenditure(((double)source.getExpenditure())); 
destination.setId(((java.lang.Long)source.getId())); 
destination.setNonCashDrawerOpenings(((int)source.getNonCashDrawerOpenings())); 
destination.setOpenBalance(((double)source.getOpenBalance())); 
destination.setReportNumber(((java.lang.String)source.getReportNumber())); 
destination.setSalesCard(((double)source.getSalesCard())); 
destination.setSalesCash(((double)source.getSalesCash())); 
destination.setSalesCredit(((double)source.getSalesCredit())); 
destination.setSalesEcCard(((double)source.getSalesEcCard())); 
destination.setSalesTotal(((double)source.getSalesTotal())); 
destination.setSalesTotalVoucher(((double)source.getSalesTotalVoucher())); 
destination.setSalesVaucher(((double)source.getSalesVaucher())); 
java.util.List new_destinationStylistBreakdown0 = null; 
if (!(((java.util.Map)source.getStylistBreakdown()) == null)) {
new_destinationStylistBreakdown0 = ((java.util.List)new java.util.ArrayList());
} else {
new_destinationStylistBreakdown0 = null;}
com.jresearchsoft.booking.ft.admin.module.shared.pos.model.StylistBreakdown stylistBreakdown_destination0Element = null; 
boolean stylistBreakdown_destination0ElementShouldBeAddedToCollector = false; if ( !(((java.util.Map)source.getStylistBreakdown()) == null)) {

java.util.Iterator stylistBreakdown_$_iter = ((java.util.Map)source.getStylistBreakdown()).entrySet().iterator(); 
while (stylistBreakdown_$_iter.hasNext()) {
java.util.Map.Entry stylistBreakdown_source0Element = ((java.util.Map.Entry)stylistBreakdown_$_iter.next()); 
if ( stylistBreakdown_destination0Element == null || !(((((java.lang.Double)stylistBreakdown_source0Element.getValue()) != null && ((double)stylistBreakdown_destination0Element.getValue()) == ((java.lang.Double)stylistBreakdown_source0Element.getValue()).java.lang.DoubleValue()))) || !(((((org.jresearch.commons.gwt.app.shared.model.user.UserModel)stylistBreakdown_destination0Element.getStylist()) != null && ((org.jresearch.commons.gwt.app.shared.model.user.UserModel)stylistBreakdown_destination0Element.getStylist()).equals(((ma.glasnost.orika.Converter)usedConverters[2]).convert(((java.lang.Long)stylistBreakdown_source0Element.getKey()), ((ma.glasnost.orika.metadata.Type)usedTypes[2]), mappingContext)))))) {

stylistBreakdown_destination0Element = ((com.jresearchsoft.booking.ft.admin.module.shared.pos.model.StylistBreakdown)((ma.glasnost.orika.BoundMapperFacade)usedMapperFacades[0]).newObject(stylistBreakdown_source0Element, mappingContext)); 
stylistBreakdown_destination0ElementShouldBeAddedToCollector = true; 
}
mappingContext.beginMapping(((ma.glasnost.orika.metadata.Type)usedTypes[3]), ((java.util.Map)source.getStylistBreakdown()), ((ma.glasnost.orika.metadata.Type)usedTypes[4]), new_destinationStylistBreakdown0);
try {

if((stylistBreakdown_destination0Element == null)) { 

stylistBreakdown_destination0Element = ((com.jresearchsoft.booking.ft.admin.module.shared.pos.model.StylistBreakdown)((ma.glasnost.orika.BoundMapperFacade)usedMapperFacades[0]).newObject(stylistBreakdown_source0Element, mappingContext)); 
}
if ( !(((java.lang.Long)stylistBreakdown_source0Element.getKey()) == null)){ 
stylistBreakdown_destination0Element.setStylist(((org.jresearch.commons.gwt.app.shared.model.user.UserModel)((ma.glasnost.orika.Converter)usedConverters[2]).convert(((java.lang.Long)stylistBreakdown_source0Element.getKey()), ((ma.glasnost.orika.metadata.Type)usedTypes[2]), mappingContext))); 
} else { 
stylistBreakdown_destination0Element.setStylist(null);
 }
if (stylistBreakdown_destination0ElementShouldBeAddedToCollector) {
new_destinationStylistBreakdown0.add(((com.jresearchsoft.booking.ft.admin.module.shared.pos.model.StylistBreakdown)stylistBreakdown_destination0Element)); 
stylistBreakdown_destination0ElementShouldBeAddedToCollector = false; 
}
if((stylistBreakdown_destination0Element == null)) { 

stylistBreakdown_destination0Element = ((com.jresearchsoft.booking.ft.admin.module.shared.pos.model.StylistBreakdown)((ma.glasnost.orika.BoundMapperFacade)usedMapperFacades[0]).newObject(stylistBreakdown_source0Element, mappingContext)); 
}
if ( !(((java.lang.Double)stylistBreakdown_source0Element.getValue()) == null)){ 
stylistBreakdown_destination0Element.setValue(((java.lang.Double)stylistBreakdown_source0Element.getValue()).doubleValue()); 
}
} finally {
  mappingContext.endMapping();
}

}}

if (!(new_destinationStylistBreakdown0 == null) && !new_destinationStylistBreakdown0.isEmpty()) {
if (((java.util.List)destination.getStylistBreakdown()) == null) {
destination.setStylistBreakdown(((java.util.List)new java.util.ArrayList())); 
} else {

((java.util.List)destination.getStylistBreakdown()).clear(); 
}

((java.util.List)destination.getStylistBreakdown()).addAll(new_destinationStylistBreakdown0); 
}

		if(customMapper != null) { 
			 customMapper.mapAtoB(source, destination, mappingContext);
		}
	}

 for ma.glasnost.orika.generated.Orika_CashReportModel_CashReportDto_Mapper94001786619754$3

javassist.CannotCompileException: [source error] no such field: java
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.compileClass(JavassistCompilerStrategy.java:254)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.compileClass(SourceCodeContext.java:245)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.getInstance(SourceCodeContext.java:262)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:73)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1333)
	at ma.glasnost.orika.impl.DefaultMapperFactory.build(DefaultMapperFactory.java:1160)
	at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:820)
	at org.jresearch.orika.spring.OrikaSpringMapper.configure(OrikaSpringMapper.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1581)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1136)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1064)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1225)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:552)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javassist.compiler.CompileError: no such field: java
	at javassist.compiler.MemberResolver.lookupField(MemberResolver.java:313)
	at javassist.compiler.MemberResolver.lookupFieldByJvmName(MemberResolver.java:299)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:876)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:860)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.TypeChecker.booleanExpr(TypeChecker.java:518)
	at javassist.compiler.TypeChecker.atBinExpr(TypeChecker.java:337)
	at javassist.compiler.ast.BinExpr.accept(BinExpr.java:41)
	at javassist.compiler.TypeChecker.booleanExpr(TypeChecker.java:527)
	at javassist.compiler.TypeChecker.atBinExpr(TypeChecker.java:337)
	at javassist.compiler.ast.BinExpr.accept(BinExpr.java:41)
	at javassist.compiler.TypeChecker.booleanExpr(TypeChecker.java:523)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:592)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.booleanExpr(TypeChecker.java:527)
	at javassist.compiler.TypeChecker.atBinExpr(TypeChecker.java:337)
	at javassist.compiler.ast.BinExpr.accept(BinExpr.java:41)
	at javassist.compiler.TypeChecker.booleanExpr(TypeChecker.java:526)
	at javassist.compiler.TypeChecker.atBinExpr(TypeChecker.java:337)
	at javassist.compiler.ast.BinExpr.accept(BinExpr.java:41)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.compileBooleanExpr(CodeGen.java:236)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:384)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atWhileStmnt(CodeGen.java:437)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:357)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:398)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
	at javassist.compiler.Javac.compileMethod(Javac.java:169)
	at javassist.compiler.Javac.compile(Javac.java:95)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
	... 55 common frames omitted
```

**Comment by andreabertagnolli** [comment]
Orika version?
I tried with the currente HEAD but I cannot reproduce the exception, can you report a complete failing test case (possibly as simple as possible)? 
thanks

**Comment by foal** [comment]
>Orika version? 
1.5.0
