### ISSUE TITLE
mapping package private classes does not work

### ISSUE THREAD

**Issue by kirviq** [orika-mapper/orika#187]
I tried to follow the guide on http://orika-mapper.github.io/orika-docs/mappings-via-classmapbuilder.html
and created the following file:
``` java
import java.util.Date;
import ma.glasnost.orika.impl.DefaultMapperFactory;
	
class BasicPerson {
	private String name;
	private int age;
	private Date birthDate;
	// getters and setters
}

class BasicPersonDto {
	private String fullName;
	private int currentAge;
	private Date birthDate;
	// getters and setters
}

public class OrikaTest {
	public static void main(String[] args) {
		DefaultMapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
		mapperFactory.classMap(BasicPerson.class, BasicPersonDto.class)
				.field("name", "fullName")
				.field("age", "currentAge")
				.register();
		mapperFactory.build();
	}
}
```
(See the attached zip for full file with getters and setters.)

It generates the following output:
```
 15:26:31.083 [main] DEBUG m.g.orika.metadata.ClassMapBuilder - ClassMap created:
	ClassMapBuilder.map(BasicPerson, BasicPersonDto)
	 .field( name(String), fullName(String) )
	 .field( age(int), currentAge(int) )
Exception in thread "main" ma.glasnost.orika.MappingException: >ma.glasnost.orika.impl.generator.CompilerStrategy$SourceCodeGenerationException: class >BasicPerson is not accessible
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:104)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1333)
	at ma.glasnost.orika.impl.DefaultMapperFactory.build(DefaultMapperFactory.java:1160)
	at OrikaTest.main(OrikaTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: ma.glasnost.orika.impl.generator.CompilerStrategy$SourceCodeGenerationException: >class BasicPerson is not accessible
	at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.assureTypeIsAccessible(JavassistCompilerStrategy.java:156)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:56)
	... 8 more
```
I used orika 1.5.0. Anything I did wrong?

**Comment by brabenetz** [comment]
Since Orika generates Java code to perform the actual mapping, it will generally follow the same restrictions of what you could write yourself. So this is not supported. Classes must be public.

**Comment by kirviq** [comment]
But I can write java code that maps this. It just needs to be in the same package. Can't orika generate the code that reads the values from the source in the source's package and the code that writes to the destination in the destinations package?

**Comment by MichalOrlowski** [comment]
Will it be released with 1.5.1 version?
