### ISSUE TITLE
NullPointerException when mapping a single property at the top level to a multioccurrence item

### ISSUE THREAD

**Issue by james23443** [orika-mapper/orika#192]
When mappinging a property on the top level object to a multioccurrence item a NullPointerException is thrown at line 413 of SourceCodeContext.java. It appears this segment of code expects this property to have a parent container, but if it is a plain property eg String on top level then source.getContainer() returns null. This is using version 1.5.0.

I worked around the problem by changing the if on line 411 to 
if (destination.getContainer() instanceof NestedProperty && source.getContainer() instanceof NestedProperty) from if (destination.getContainer() instanceof NestedProperty)

Example
.field("people.defaultPersonType", "userList[0].employees{personType}")

Exception in thread "main" ma.glasnost.orika.MappingException: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:104)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1333)
	at ma.glasnost.orika.impl.DefaultMapperFactory.build(DefaultMapperFactory.java:1160)
	at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:820)
	at ma.glasnost.orika.impl.ConfigurableMapper.init(ConfigurableMapper.java:121)
	at ma.glasnost.orika.impl.ConfigurableMapper.<init>(ConfigurableMapper.java:97)
	at au.gov.nsw.police.tins.bean.mapping.TinPayloadToEventMapper.<init>(TinPayloadToEventMapper.java:22)
	at au.gov.nsw.police.tins.bean.mapping.EventMapping.main(EventMapping.java:55)
Caused by: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.VariableRef.<init>(VariableRef.java:83)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.assureContainerInstanceExists(SourceCodeContext.java:413)
	at ma.glasnost.orika.impl.generator.specification.MultiOccurrenceToMultiOccurrence.generateMultiOccurrenceMapping(MultiOccurrenceToMultiOccurrence.java:112)
	at ma.glasnost.orika.impl.generator.specification.MultiOccurrenceToMultiOccurrence.generateMappingCode(MultiOccurrenceToMultiOccurrence.java:75)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.mapAggregateFields(SourceCodeContext.java:722)
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:182)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:70)
	... 7 more

**Comment by visola** [comment]
For posterity.
I ran into this issue and got it solved after updating to the latest version.
I was on 1.4.2 and updated to 1.5.4.
