### ISSUE TITLE
Convert a Date to a java8 LocalDate

### ISSUE THREAD

**Issue by M3lkior** [orika-mapper/orika#198]
Hi Everybody,
    
I try to do a bi-directional convertion between a `java.util.Date` and the new java8 `java.time.LocalDate`
    
Here is my Orika configuration (with spring) : 
    
```java
    
	@Bean
	public MapperFacade orikaBeanMapper() {
		
		ConverterFactory converterFactory = mapperFactory.getConverterFactory();

		converterFactory.registerConverter("DateConverter", new OrikaDateConverter());
		
		MapperFacade mapper = mapperFactory.getMapperFacade();
		return mapper;
	}
``` 
        
Here my DateConverter : 
        
```java
        
public class OrikaDateConverter extends BidirectionalConverter<Date,LocalDate> {


	
	@Override
	public LocalDate convertTo(Date source, Type<LocalDate> destinationType, MappingContext mappingContext) {
		//return source.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		Instant instant = Instant.ofEpochMilli(source.getTime());
		LocalDate res = LocalDateTime.ofInstant(instant, ZoneId.systemDefault()).toLocalDate();
		return res;
	}

	@Override
	public Date convertFrom(LocalDate source, Type<Date> destinationType, MappingContext mappingContext) {
		Instant instant = source.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant();
		Date res = Date.from(instant);
		return res;
		
	}
}

```
        
When i try to convert my objects, i have this error with this simple test 
        
```java 
        @Autowired
	MapperFacade orikaBeanMapper;
	
	@Test
	public void testDateConversion(){
		Date now = new Date();
		orikaBeanMapper.map(now, LocalDate.class);
	}

```
        
```
        ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceType = java.util.Date
destinationType = java.time.LocalDate
Error occurred: ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceType = java.time.LocalDate
sourceProperty = month(Month)
destinationType = java.util.Date
destinationProperty = month(int)
Error occurred: ma.glasnost.orika.MappingException: Encountered mapping of primitive to object (or vise-versa); sourceType=Month, destinationType=int
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:104)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1333)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:718)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:572)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:179)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:675)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:655)
	at com.adeoservices.pas.thetis.api.common.OrikaMapperTests.testDateConversion(OrikaMapperTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceType = java.time.LocalDate
sourceProperty = month(Month)
destinationType = java.util.Date
destinationProperty = month(int)
Error occurred: ma.glasnost.orika.MappingException: Encountered mapping of primitive to object (or vise-versa); sourceType=Month, destinationType=int
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:170)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:71)
	... 36 more
Caused by: ma.glasnost.orika.MappingException: Encountered mapping of primitive to object (or vise-versa); sourceType=Month, destinationType=int
	at ma.glasnost.orika.impl.generator.specification.PrimitiveAndObject.generateMappingCode(PrimitiveAndObject.java:60)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.mapFields(SourceCodeContext.java:778)
	at ma.glasnost.orika.impl.generator.MapperGenerator.generateFieldMapCode(MapperGenerator.java:247)
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:167)
	... 37 more
```

Any idea ?

**Comment by M3lkior** [comment]
Solved when register converter globally (without a name) ...

```java
converterFactory.registerConverter(new OrikaDateConverter());

```
