### ISSUE TITLE
Unmodifiable collections and transformation

### ISSUE THREAD

**Issue by kotovdv** [orika-mapper/orika#200]
Hi. I'm facing the following issue when working with unmodifiable collections in my classes.

Consider the following code:

**We have two types** 

- Class which represents simple item with id field
```
public class ItemDTO {

    private final Long id;

    public ItemDto(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }
}

```

- Class which represents collection of items

```
public class CollectionDTO {

    private List<ItemDTO> items = new ArrayList<>();

    public CollectionDTO(Collection<ItemDTO> items) {
        this.items.addAll(items);
    }

    public Collection<ItemDTO> getItems() {
        return Collections.unmodifiableList(items);
    }
}
```

And we have absolutely similar in terms of fields  ***CollectionEntity*** and ***ItemEntity*** model.

```
public class CollectionEntity {

    private List<ItemEntity> items = new ArrayList<>();

    public CollectionEntity(Collection<ItemEntity> items) {
        this.items.addAll(items);
    }

    public Collection<ItemEntity> getItems() {
        return Collections.unmodifiableList(items);
    }
}
```

```
public class ItemEntity {

    private final Long id;

    public ItemEntity(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }
}
```

- Mapper is configured in the following way:

```
private static MapperFacade getMapper() {
        MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();

        mapperFactory.classMap(ItemEntity.class, ItemDTO.class)
                .constructorA("id")
                .constructorB("id")
                .field("id", "id")
                .register();

        mapperFactory.classMap(CollectionEntity.class, CollectionDTO.class)
                .constructorA("items")
                .constructorB("items")
                .field("items", "items")
                .register();

        return mapperFactory.getMapperFacade();
    }

```

And in the end i'm trying to execute the following piece of code:

```
public static void main(String[] args) {
        CollectionEntity collectionEntity = new CollectionEntity(asList(
                new ItemEntity(2L),
                new ItemEntity(3L),
                new ItemEntity(4L))
        );

        getMapper().map(collectionEntity, CollectionDTO.class);
}
```

Which produces the following stacktrace:

```
Exception in thread "main" ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceClass = class com.jindex.crawler.engine.entity.CollectionEntity
destinationType = com.jindex.crawler.engine.dto.CollectionDTO
resolvedStrategy = InstantiateAndUseCustomMapperStrategy<CollectionEntity, CollectionDTO> {customMapper: GeneratedMapper<CollectionEntity, CollectionDTO> {usedConverters: [], usedMappers: [], usedMapperFacades: [], usedTypes: [ItemEntity, ItemDTO] }, unenhancer: ma.glasnost.orika.unenhance.BaseUnenhancer@31c88ec8, objectFactory: ma.glasnost.orika.generated.CollectionDTO_CollectionEntity_ObjectFactory438035385652099438035595686222$5@1cbbffcd}
Error occurred: java.lang.UnsupportedOperationException
	at ma.glasnost.orika.impl.ExceptionUtility.newMappingException(ExceptionUtility.java:55)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:686)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:655)
	at com.jindex.crawler.engine.MapperTest.main(MapperTest.java:27)
Caused by: java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.clear(Collections.java:1074)
	at ma.glasnost.orika.generated.Orika_CollectionDTO_CollectionEntity_Mapper438035561060319$1.mapAtoB(Orika_CollectionDTO_CollectionEntity_Mapper438035561060319$1.java)
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:72)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:676)
	... 2 more
```

Apparently, Orika is trying to clear one of the inner collections, that were created in the process of transformation resulting in **UnsupportedOperationException**, which is produced by **UnmodifiableList**. Is there any way around it besides creating custom mappers?

**Comment by elaatifi** [comment]
In fact there is a quite few strategies to handle a collection mapping:

1. - clear and copy new mapped objects
2. - merge new and old collections (custom logic)
3. - just overwrite target collection (only used when target collection is NULL)

For various reasons (not all good) only the first strategy has been implemented and used by default. For the remaining strategies you need to register a custom Collection Mapper. There is some examples out there that show how we can do it.

Maybe we can use the third strategy in case of Unmodifiable or immutable collections but there is no reliable way to "know" if a collection is modifiable or not. Sure we can do that for JDK unmodifiable collections not for the others ... so it make sens that it should remain an user decision

**Comment by jorgebo10** [comment]
Hi, i'm facing the same issue and i would like to implement option 2. Could you suggest how to start doing it? Thanks, Jorge

**Comment by melote** [comment]
facing same problems while transforms to grpc object, don't know how to fix it.

**Comment by jsbxyyx** [comment]
I see same problems from grpc object. at what time fixed it.
