### ISSUE TITLE
ClassNotFoundException: ma.glasnost.orika.impl.GeneratedMapperBase on websphere

### ISSUE THREAD

**Issue by dickerpulli** [orika-mapper/orika#226]
I have the problem, that die runtime compile of the mapper classes does not work on websphere server. With deployment on local tomcat all works fine.

I think it's a problem with class loading on websphere that differs from tomcat class loading.

Are there any hints?

By the way: The orika-1.5.1.jar **is included** in WEB-INF/libs folder of the deployed war file.

Stacktrace:
ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceType = com.provinzial.protago.gewerbe.bestandssystem.model.pff.vertragsbuendel.Nachlass
destinationType = com.provinzial.protago.gewerbe.plattform.model.pff.domain.Nachlass
Error occurred: ma.glasnost.orika.impl.generator.CompilerStrategy$SourceCodeGenerationException: Error compiling ma.glasnost.orika.generated.Orika_Nachlass_Nachlass_Mapper1500359820831174125$38
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:104)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1480)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:740)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:567)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:179)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapElement(MapperFacadeImpl.java:790)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:621)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsSet(MapperFacadeImpl.java:413)
	at ma.glasnost.orika.generated.Orika_Vertrag_GewerbeBuendelbaustein_Mapper1500359803936798000$3.mapBtoA(Orika_Vertrag_GewerbeBuendelbaustein_Mapper1500359803936798000$3.java)
	at ma.glasnost.orika.impl.GeneratedMapperBase.mapBtoA(GeneratedMapperBase.java:150)
	at ma.glasnost.orika.generated.Orika_BetriebUndBerufHaftpflicht_BetriebUndBerufHaftpflicht_Mapper1500359804428312375$23.mapBtoA(Orika_BetriebUndBerufHaftpflicht_BetriebUndBerufHaftpflicht_Mapper1500359804428312375$23.java)
	at ma.glasnost.orika.impl.ReversedMapper.mapAtoB(ReversedMapper.java:65)
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:77)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:251)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapElement(MapperFacadeImpl.java:797)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:621)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsSet(MapperFacadeImpl.java:413)
	at ma.glasnost.orika.generated.Orika_Vertragsbuendel_GewerbeBuendel_Mapper1500359804456818125$24.mapBtoA(Orika_Vertragsbuendel_GewerbeBuendel_Mapper1500359804456818125$24.java)
	at ma.glasnost.orika.impl.ReversedMapper.mapAtoB(ReversedMapper.java:65)
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:77)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:671)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:650)
	at com.provinzial.protago.allsparten.plattform.common.mapper.AbstractMapper.map(AbstractMapper.java:63)
	at com.provinzial.protago.gewerbe.bestandssystem.model.pff.mapper.DomainVertragsbuendelMapper.map(DomainVertragsbuendelMapper.java:257)
	at com.provinzial.protago.gewerbe.batch.vz_klauselnbedingungen.migration.Ablauf02VertragsbuendelMigrierenProcessor.process(Ablauf02VertragsbuendelMigrierenProcessor.java:115)
	at com.provinzial.protago.gewerbe.batch.vz_klauselnbedingungen.migration.Ablauf02VertragsbuendelMigrierenProcessor.process(Ablauf02VertragsbuendelMigrierenProcessor.java:53)
	at com.provinzial.protago.gewerbe.batch.vz_klauselnbedingungen.migration.Ablauf02VertragsbuendelMigrierenProcessor$$FastClassBySpringCGLIB$$b4988996.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:708)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644)
	at com.provinzial.protago.gewerbe.batch.vz_klauselnbedingungen.migration.Ablauf02VertragsbuendelMigrierenProcessor$$EnhancerBySpringCGLIB$$668732c8.process(<generated>)
	at com.provinzial.protago.gewerbe.batch.vz_klauselnbedingungen.migration.Ablauf02VertragsbuendelMigrierenProcessor$$FastClassBySpringCGLIB$$b4988996.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:708)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644)
	at com.provinzial.protago.gewerbe.batch.vz_klauselnbedingungen.migration.Ablauf02VertragsbuendelMigrierenProcessor$$EnhancerBySpringCGLIB$$668732c8.process(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy1248.process(Unknown Source)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doProcess(SimpleChunkProcessor.java:126)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.transform(SimpleChunkProcessor.java:293)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:192)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at com.provinzial.framework.util.jta.ProvinzialWebSphereUowTransactionManagerBuilder$1$1.doInTransaction(ProvinzialWebSphereUowTransactionManagerBuilder.java:33)
	at org.springframework.transaction.jta.WebSphereUowTransactionManager$UOWActionAdapter.run(WebSphereUowTransactionManager.java:345)
	at com.ibm.ws.uow.embeddable.EmbeddableUOWManagerImpl.runUnderNewUOW(EmbeddableUOWManagerImpl.java:791)
	at com.ibm.ws.uow.embeddable.EmbeddableUOWManagerImpl.runUnderUOW(EmbeddableUOWManagerImpl.java:370)
	at org.springframework.transaction.jta.WebSphereUowTransactionManager.execute(WebSphereUowTransactionManager.java:288)
	at com.provinzial.framework.util.jta.ProvinzialWebSphereUowTransactionManagerBuilder$1.execute(ProvinzialWebSphereUowTransactionManagerBuilder.java:38)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:392)
	at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
	at com.provinzial.framework.batch.service.BatchContainerServiceImpl$JobProxy.execute(BatchContainerServiceImpl.java:76)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
	at org.springframework.scheduling.commonj.DelegatingWork.run(DelegatingWork.java:62)
	at com.ibm.ws.asynchbeans.J2EEContext$RunProxy.run(J2EEContext.java:267)
	at java.security.AccessController.doPrivileged(AccessController.java:594)
	at com.ibm.ws.asynchbeans.J2EEContext.run(J2EEContext.java:1165)
	at com.ibm.ws.asynchbeans.WorkWithExecutionContextImpl.go(WorkWithExecutionContextImpl.java:199)
	at com.ibm.ws.asynchbeans.CJWorkItemImpl.run(CJWorkItemImpl.java:236)
	at com.ibm.ws.asynchbeans.WLMCJWorkItemImpl.run(WLMCJWorkItemImpl.java:69)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1881)
Caused by: ma.glasnost.orika.impl.generator.CompilerStrategy$SourceCodeGenerationException: Error compiling ma.glasnost.orika.generated.Orika_Nachlass_Nachlass_Mapper1500359820831174125$38
	at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.compileClass(JavassistCompilerStrategy.java:257)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.compileClass(SourceCodeContext.java:245)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.getInstance(SourceCodeContext.java:262)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:73)
	... 89 more
Caused by: javassist.CannotCompileException: by java.lang.NoClassDefFoundError: ma.glasnost.orika.impl.GeneratedMapperBase
	at javassist.ClassPool.toClass(ClassPool.java:1170)
	at javassist.CtClass.toClass(CtClass.java:1316)
	at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.compileClass(JavassistCompilerStrategy.java:250)
	... 92 more
Caused by: java.lang.NoClassDefFoundError: ma.glasnost.orika.impl.GeneratedMapperBase
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:349)
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at javassist.ClassPool.toClass2(ClassPool.java:1183)
	at javassist.ClassPool.toClass(ClassPool.java:1164)
	... 94 more
Caused by: java.lang.ClassNotFoundException: ma.glasnost.orika.impl.GeneratedMapperBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:607)
	at com.ibm.ws.bootstrap.ExtClassLoader.authorizedFindClass(ExtClassLoader.java:264)
	at com.ibm.ws.bootstrap.ExtClassLoader.findClass(ExtClassLoader.java:241)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:844)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:823)
	at com.ibm.ws.bootstrap.ExtClassLoader.loadClass(ExtClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:803)
	... 101 more

**Comment by elaatifi** [comment]
Hello,
This looks like a ClassLoader issue, you should try this workaround :
subclass JavassistCompilerStrategy and set it manually in your code:
new DefaultMapperFactory.Builder().compilerStrategy(new YourCustomJavassistCompilerStrategy()).build() 

just declare YourCustomJavassistCompilerStrategy extends JavassistCompilerStrategy {} (some where)

_I don't use WebSphere and can't test it._

**Comment by dickerpulli** [comment]
The custom simple "extends JavassistCompilerStrategy" have not worked. I tried it.

My workaround by now: I use EclipseJdtCompilerStrategy.

**Comment by dickerpulli** [comment]
No need to solve the problem any more
