### ISSUE TITLE
BigDecimal to Integer mapping

### ISSUE THREAD

**Issue by djemalmohamed** [orika-mapper/orika#229]
Hello,
I have two objects for mapping, the first object contains a several BigDecimal fields (Source Object) and the second one contains the same fields but defined as Integer (Destination Object).

When executing the mapping between these two objects, an exception will be triggered: 

Exception in thread "main" ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceType = java.math.BigDecimal
destinationType = java.lang.Integer
Error occurred: No converter registered for conversion from BigDecimal to Integer, nor any ObjectFactory which can generate Integer from BigDecimal
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:728)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:567)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:179)
	at ma.glasnost.orika.impl.DefaultBoundMapperFacade$BoundStrategyCache.getStrategy(DefaultBoundMapperFacade.java:259)
	at ma.glasnost.orika.impl.DefaultBoundMapperFacade.map(DefaultBoundMapperFacade.java:137)
	at ma.glasnost.orika.generated.Orika_ContratCDDMsg_Contratcdd_Mapper4444947994763$0.mapAtoB(Orika_ContratCDDMsg_Contratcdd_Mapper4444947994763$0.java)
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:77)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:671)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:650)

Any solutions please? Especially without using customize() to map each field alone.

Thanks already.

Mohamed DJEMAL

**Comment by djemalmohamed** [comment]
It's OK, I need to use custom converter:

**Comment by qixiaobo** [comment]
BuiltIn
