### ISSUE TITLE
java.lang.NoClassDefFoundError: com/googlecode/concurrentlinkedhashmap/ConcurrentLinkedHashMap$Builder

### ISSUE THREAD

**Issue by JorgeRdg** [orika-mapper/orika#233]
Trying to use latest version of Orika Mapper with Dropwizard 8 has thrown the following error:
```
java.lang.NoClassDefFoundError: com/googlecode/concurrentlinkedhashmap/ConcurrentLinkedHashMap$Builder

	at ma.glasnost.orika.util.HashMapUtility.getConcurrentLinkedHashMap(HashMapUtility.java:45)
	at ma.glasnost.orika.converter.DefaultConverterFactory.<init>(DefaultConverterFactory.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at ma.glasnost.orika.impl.UtilityResolver.resolveUtility(UtilityResolver.java:131)
	at ma.glasnost.orika.impl.UtilityResolver.getDefaultConverterFactory(UtilityResolver.java:61)
	at ma.glasnost.orika.impl.DefaultMapperFactory$MapperFactoryBuilder.<init>(DefaultMapperFactory.java:283)
	at ma.glasnost.orika.impl.DefaultMapperFactory$Builder.<init>(DefaultMapperFactory.java:564)
(...)
```

Any idea?

This is the running code that fails:
```public class Mappings {
  public static MapperFacade configure() {
    return new MappingsBuilder()
        // Polymorphic models
        .map(class1.class, class2.class)
        .build();
  }

  public static class MappingsBuilder {
    private final MapperFactory factory;

    public MappingsBuilder() {
      factory = new DefaultMapperFactory.Builder().build();

      // Don't try to map DateTime <-> DateTime
      factory
          .getConverterFactory()
          .registerConverter(new PassThroughConverter(DateTime.class));
    }

    public <A, B> MappingsBuilder map(Class<A> typeA, Class<B> typeB) {
      factory
          .classMap(typeA, typeB)
          .byDefault()
          .register();
      return this;
    }

    public MapperFacade build() {
      return factory.getMapperFacade();
    }
  }
}```

**Comment by elaatifi** [comment]
Nothing seems wrong with your code. Please check your classpath

**Comment by aneeshmunnam** [comment]
What is the version of Orika mapper you are using?
