### ISSUE TITLE
PropertyNotFoundException if source object has no constructor with a parameter for the property not found

### ISSUE THREAD

**Issue by rubin55** [orika-mapper/orika#234]
When trying to convert from the following class(es):

```
public class XOrderSearchResultRecordType {
    protected AdsType ads;
    //getter, setter
}

...

public class AdsType {
    protected List<XAdRecord> xAdRecord;
    //getter, setter
```

Using the following configuration:

```
    public void configure(MapperFactory factory) {
        factory .classMap(XOrderSearchResultRecordType.class, Target.class)
                .field("ads.xAdRecord", "targetField").register();
    }
}
```

I get a PropertyNotFoundException on "xAdRecord". Curiously, specifying the name of the field as XAdRecord (notice the capital X) makes Orika work. Also, adding a constructor to AdsType above with xAdRecord as a parameter will make Orika work (happens in PropertyResolver.getProperty(...) on line 706). Stacktrace:

```
Caused by: ma.glasnost.orika.MappingException: ClassMapBuilder.map(XOrderSearchResultRecordType, AdOrder).field('ads.xAdRecord', 'placement'): Error: could not resolve nested property [ads.xAdRecord] on XOrderSearchResultRecordType, because xAdRecord does not belong to AdsType
	at ma.glasnost.orika.metadata.ClassMapBuilder.fieldMap(ClassMapBuilder.java:338)
	at ma.glasnost.orika.metadata.ClassMapBuilder.fieldMap(ClassMapBuilder.java:311)
	at ma.glasnost.orika.metadata.ClassMapBuilder.field(ClassMapBuilder.java:249)
	at net.persgroep.adhub.converter.XOrderSearchResultRecordTypeMappingConfigurer.configure(XOrderSearchResultRecordTypeMappingConfigurer.java:18)
	at net.persgroep.adhub.converter.OrikaModelMapper.configureNewMapperFacade(OrikaModelMapper.java:51)
	at net.persgroep.adhub.converter.OrikaModelMapper.setApplicationContext(OrikaModelMapper.java:78)
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:121)
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:97)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	... 74 more
Caused by: ma.glasnost.orika.PropertyNotFoundException: could not resolve nested property [ads.xAdRecord] on XOrderSearchResultRecordType, because xAdRecord does not belong to AdsType
	at ma.glasnost.orika.property.PropertyResolver.getNestedProperty(PropertyResolver.java:500)
	at ma.glasnost.orika.property.PropertyResolver.getProperty(PropertyResolver.java:676)
	at ma.glasnost.orika.property.PropertyResolver.getProperty(PropertyResolver.java:634)
	at ma.glasnost.orika.metadata.ClassMapBuilder.resolveProperty(ClassMapBuilder.java:879)
	at ma.glasnost.orika.metadata.FieldMapBuilder.<init>(FieldMapBuilder.java:78)
	at ma.glasnost.orika.metadata.FieldMapBuilder.<init>(FieldMapBuilder.java:61)
	at ma.glasnost.orika.metadata.ClassMapBuilder.fieldMap(ClassMapBuilder.java:328)
	... 84 more
```

**Comment by rubin55** [comment]
I figured out what is happening.

In IntrospectorPropertyResolver.collectProperties, Introspector.getBeanInfo(type) is executed to get the BeanInfo. A part of that is initializing PropertyDescriptor(s), which contains a constructor that sets the name of the property using Introspector.decapitalize(base). The decapitalize method contains a rule that sets the first letter in the name to lowercase, if the first character is upper and the second character is *not* - if the name is contains two or more consecutive uppercase characters in the beginning, it will return the name as is, unmodified.

This also explains why the property array as used by PropertyResolver contains a lowercase "class" entry: The BeanInfo's PropertyResolver originally contained Class and XAdRecord; Class is decapitalized because there is only one capital in the original string; XAdRecord stays XAdRecord because the second character is a capital.

Since Introspector is a part of the JRE, I'm not sure if this is intended behaviour. Regardless, I find it very unintuitive from a point of view as an Orika user (i.e, nothing tells me that this is why my member field is not found).

**Comment by rubin55** [comment]
Additional information: the initial base name passed to the PropertyDescriptor constructor is actually name.substring(2) (in the case of a boolean method isSomething) or name.substring(3) in the case of getSomething / setSomething.

This means that the initial name that is used to construct the PropertyDescriptor is not a field name, but litterally a part of the is/get/set method; The constructor of PropertyDescriptor seems to expect that and belatedly tries to decapitalize the string passed (PropertyDescriptor.java, line 159: setName(Introspector.decapitalize(base)); ), however, this never happens in the case that two or more characters in the beginning of the are capitalized, leaving the string as is, resulting in a wrong field name, and explaining the haphazard difffernces in properties starting with a lowercase letter and some starting with capitals.

**Comment by rubin55** [comment]
I actually consider this a bug in Introspector.decapitalize. I filed a bug in the JDK. Don't know if they would ever fix that, but hey, you never know. In the meantime, I'm going to try another mapping framework.

**Comment by rubin55** [comment]
Argh.. from the JavaBeans 1.01 spec document, section 8.8: capitalization of inferred names:

"When we use design patterns to infer a property or event name, we need to decide what rules to follow for capitalizing the inferred name. If we extract the name from the middle of a normal mixedCase style Java name then the name will, by default, begin with a capital letter.
Java programmers are accustomed to having normal identifiers start with lower case letters. Vigorous reviewer input has convinced us that we should follow this same conventional rule for property and event names.

Thus when we extract a property or event name from the middle of an existing Java name, we normally convert the first character to lower case. However to support the occasional use of all upper-case names, we check if the first two characters of the name are both upper case and if so leave it alone. So for example,
“FooBah” becomes “fooBah” “Z” becomes “z”
“URL” becomes “URL”

We provide a method Introspector.decapitalize which implements this conversion rule."

I consider this is a bug in the specification (which dates from '97), but I have no illusion that that will ever be fixed.. Alas, maybe someone else will run into this issue and bump into this ticket. I hope the above clarifies why capitalization of a field might or might not happen.

**Comment by elaatifi** [comment]
We've introduced RegexPropertyResolver to support your own convention:
https://orika-mapper.github.io/orika-docs/extensibility.html
