### ISSUE TITLE
Mapping class with additional private constructor prints error

### ISSUE THREAD

**Issue by BlueIce** [orika-mapper/orika#246]
When i try to map a class with a no-arg public constructor _and_ a private constructor with arguments an error is printed. However the mapping is still successful.

Here is an example:
```java
public class A {

    private X x;

    public X getX() {
        return x;
    }

    public void setX(X x) {
        this.x = x;
    }
    
}
```
```java
public class B {

    private X x;

    public X getX() {
        return x;
    }

    public void setX(X x) {
        this.x = x;
    }
    
}
```
```java
public class X {
    
    private Integer i;
    
    public static X create(Integer i) {
        return new X(i);
    }

    public X() {
    }
    
    private X(Integer i) {
        this.i = i;
    }

    public Integer getI() {
        return i;
    }

    public void setI(Integer i) {
        this.i = i;
    }

}
```

```java
ConfigurableMapper mapper = new ConfigurableMapper();
        
A a = new A();
a.setX(X.create(10));
        
B b = mapper.map(a, B.class);
```

This behaviour was first introduced in version 1.5.1 and still exists in 1.5.2.

<details>
 <summary>Error message</summary>

```
ERROR [main] (JavassistCompilerStrategy.java:243) - An exception occured while compiling the following method:

 public Object create(Object s, ma.glasnost.orika.MappingContext mappingContext) {if(s == null) throw new java.lang.IllegalArgumentException("source object must be not null");if (s instanceof github.orika.X) {github.orika.X source = (github.orika.X) s;
try {

java.lang.Integer arg0 = null; 
arg0 = ((java.lang.Integer)source.getI()); return new github.orika.X(arg0);
} catch (java.lang.Exception e) {

if (e instanceof RuntimeException) {

throw (RuntimeException)e;

} else {
throw new java.lang.RuntimeException("Error while constructing new X instance", e);
}
}
}return new github.orika.X();
}

 for github.orika.X_X_ObjectFactory55459170499035546147499017$2

javassist.CannotCompileException: [source error] the called constructor is private in github.orika.X
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.compileClass(JavassistCompilerStrategy.java:241)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.compileClass(SourceCodeContext.java:245)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.getInstance(SourceCodeContext.java:262)
	at ma.glasnost.orika.impl.generator.ObjectFactoryGenerator.build(ObjectFactoryGenerator.java:91)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupObjectFactory(DefaultMapperFactory.java:1067)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:182)
	at ma.glasnost.orika.impl.DefaultBoundMapperFacade$BoundStrategyCache.getStrategy(DefaultBoundMapperFacade.java:259)
	at ma.glasnost.orika.impl.DefaultBoundMapperFacade.map(DefaultBoundMapperFacade.java:137)
	at ma.glasnost.orika.generated.Orika_B_A_Mapper5546056585591$0.mapAtoB(Orika_B_A_Mapper5546056585591$0.java)
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:77)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:671)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:650)
	at ma.glasnost.orika.impl.ConfigurableMapper.map(ConfigurableMapper.java:158)
[...]

Caused by: compile error: the called constructor is private in github.orika.X
	at javassist.compiler.MemberCodeGen.getAccessibleConstructor(MemberCodeGen.java:709)
	at javassist.compiler.MemberCodeGen.atMethodCallCore2(MemberCodeGen.java:610)
	at javassist.compiler.MemberCodeGen.atMethodCallCore(MemberCodeGen.java:589)
	at javassist.compiler.MemberCodeGen.atNewExpr(MemberCodeGen.java:302)
	at javassist.compiler.ast.NewExpr.accept(NewExpr.java:73)
	at javassist.compiler.CodeGen.compileExpr(CodeGen.java:230)
	at javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:615)
	at javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:425)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:363)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.MemberCodeGen.atTryStmnt(MemberCodeGen.java:204)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:367)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:398)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
	at javassist.compiler.Javac.compileMethod(Javac.java:169)
	at javassist.compiler.Javac.compile(Javac.java:95)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
	... 38 more
```
</details>

**Comment by stapetro** [comment]
You can try the [object factory](https://orika-mapper.github.io/orika-docs/object-factories.html) approach.

**Comment by BlueIce** [comment]
Using an object factory indeed does not show the error any more.

Nevertheless i would argue that in the example above Orika should not print an error if it can successfully fall back to another public constructor.
