### ISSUE TITLE
mapping a map object error when register a fillter

### ISSUE THREAD

**Issue by nickycheng** [orika-mapper/orika#266]
example code:

```
    public static void main(String[] args) {
        MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
        mapperFactory.registerFilter(new IteratorIgnoreFilter());
        MapperFacade mapper = mapperFactory.getMapperFacade();
        Foo foo = new Foo();
        mapper.map(foo, TypeFactory.valueOf(Foo.class), TypeFactory.valueOf(Foo.class));
    }

    private static class IteratorIgnoreFilter extends NullFilter<Object, Object> {
        @Override
        public boolean shouldMap(Type sourceType, String sourceName, Object source, Type destType, String destName, Object dest, MappingContext mappingContext) {
            return !(source instanceof Iterator);
        }
    }

    public static class Foo {
        private Map<String, String> maps;
        public Map<String, String> getMaps() {
            return maps;
        }
        public void setMaps(Map<String, String> maps) {
            this.maps = maps;
        }
    }
```

error throw:

```
Error occurred: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:170)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:70)
	... 8 more
Caused by: java.lang.NullPointerException
	at ma.glasnost.orika.CustomFilter.appliesTo(CustomFilter.java:88)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.getFilter(SourceCodeContext.java:940)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.applyFilters(SourceCodeContext.java:816)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.mapFields(SourceCodeContext.java:772)
	at ma.glasnost.orika.impl.generator.specification.MapToMap.generateMappingCode(MapToMap.java:86)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.mapFields(SourceCodeContext.java:778)
	at ma.glasnost.orika.impl.generator.MapperGenerator.generateFieldMapCode(MapperGenerator.java:247)
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:167)

```

**Comment by nickycheng** [comment]
duplicate with #232 
but wonder why not merge to release
