### ISSUE TITLE
Double Nested List Exception "a{b{c}}"

### ISSUE THREAD

**Issue by robotgruntxd** [orika-mapper/orika#271]
I dont know if orika suppose to map properties like this: 
.field("singlealist{childalist{names}}", {childblist{nombres}}")

Here i got a test that explain the problem.

`  @Test
  public void orikatest() {
    ParentA parentA = new ParentA();
    SingleA singleA = new SingleA();
    ChildA childA = new ChildA();

    childA.setNames(new ArrayList<>());
    childA.getNames().add("Jorge");
    childA.getNames().add("Diego");
    childA.getNames().add("Alguien");

    singleA.setChildalist(new ArrayList<>());
    singleA.getChildalist().add(childA);

    parentA.setSinglealist(new ArrayList<>());
    parentA.getSinglealist().add(singleA);

    MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
    mapperFactory.classMap(ParentA.class, ParentB.class)
        .field("singlealist{childalist{names}}",
            "singleblist{childblist{nombres}}")
        .register();
    MapperFacade mapper = mapperFactory.getMapperFacade();
    ParentB parentB = mapper.map(parentA,ParentB.class);
    
  }`
and got:
`ma.glasnost.orika.MappingException: java.lang.NullPointerException

	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:104)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1478)
	at ma.glasnost.orika.impl.DefaultMapperFactory.build(DefaultMapperFactory.java:1293)
	at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:881)
	at ma.glasnost.orika.test.jdk8.noUpload.OrikaTest.orikatest(OrikaTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.specification.MultiOccurrenceToMultiOccurrence.registerClassMaps(MultiOccurrenceToMultiOccurrence.java:397)
	at ma.glasnost.orika.impl.generator.specification.MultiOccurrenceToMultiOccurrence.generateMappingCode(MultiOccurrenceToMultiOccurrence.java:72)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.mapAggregateFields(SourceCodeContext.java:702)
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:182)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:70)
	... 26 more`

I made some research and find out that the problem begin with this code in Node.java:335 

`                    for (p+=1; p < len; ++p) {
currentNode = new Node(path.get(p), parentNode, useSource, totalNodes);
                        parentNode = currentNode;
                    }`

I replace it with `Node(path.get(p),map, parentNode, useSource, totalNodes)` , but got other issues in MultiOccurrenceToMultiOccurrence.java:198, because the function `Node.findFieldMap(fieldMap, sourceNodes, true).parent` is not properly working.

Any suggestions?

**Comment by bawfnje** [comment]
I met too. Did you solve it?
