### ISSUE TITLE
StackOverflowError when using ScoringClassMapBuilder/CaseInsensitiveClassMapBuilder

### ISSUE THREAD

**Issue by sivetic** [orika-mapper/orika#275]
Mapping of classes that contain a List (or array) of same type results in a StackOverflowError.  

Code has been tested with 1.5.2 and 1.4.5, both releases have the same issue.  A previous commit fixed the issue, however it has since been reverted:

Fix: https://github.com/orika-mapper/orika/commit/c0c0ad98e84bcc9945c173c01888b4a7792aac25?diff=split
Revert: https://github.com/orika-mapper/orika/commit/01c5fb6fc1fa3cc32c0f192696c758bf66c7f1d5?diff=split

Exception:

```
java.lang.StackOverflowError
	at ma.glasnost.orika.metadata.ClassMapBuilder.getPropertyExpressions(ClassMapBuilder.java:149)
	at ma.glasnost.orika.metadata.ClassMapBuilder.getPropertyExpressions(ClassMapBuilder.java:177)
	at ma.glasnost.orika.metadata.ClassMapBuilder.getPropertyExpressions(ClassMapBuilder.java:177)
....
```

Test:

```
public class StackOverflowTest {
    @Test
    public void test() {
        MapperFactory mapperFactory = new DefaultMapperFactory.Builder()
                .classMapBuilderFactory(new CaseInsensitiveClassMapBuilder.Factory())
                .build();

        Source source = new Source(1);
        mapperFactory.getMapperFacade().map(source, Source.class);
    }
}

class Source {
    Source(int count) {
        this.count = count;
    }

    private List<Source> children = new ArrayList<>();

    public List<Source> getChildren() {
        return children;
    }

    public void setChildren(List<Source> children) {
        this.children = children;
    }

    private int count;

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }
}

```

**Comment by phiob** [comment]
I can also reproduce the bug when using

``` Java
MapperFactory mapperFactory = new DefaultMapperFactory.Builder()
                .classMapBuilderFactory(new CaseInsensitiveClassMapBuilder.Factory())
                .build();
```
