### ISSUE TITLE
can not convert map field to java bean when field types are different

### ISSUE THREAD

**Issue by huwsun** [orika-mapper/orika#282]
When convert a hashmap to bean, if field type is different,will cause exception:
````java
Exception in thread "main" ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceClass = class java.util.HashMap
destinationType = Company
resolvedStrategy = InstantiateAndUseCustomMapperStrategy<HashMap<Object, Object>, Company> {customMapper: GeneratedMapper<HashMap<Object, Object>, Company> {usedConverters: [], usedMappers: [], usedMapperFacades: [], usedTypes: [] }, unenhancer: ma.glasnost.orika.unenhance.BaseUnenhancer@d706f19, objectFactory: DefaultConstructorObjectFactory<Company>}
Error occurred: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at ma.glasnost.orika.impl.ExceptionUtility.newMappingException(ExceptionUtility.java:55)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:681)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:650)
	at test.main(test.java:112)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at ma.glasnost.orika.generated.Orika_Company_HashMap_Mapper81618898361876$0.mapAtoB(Orika_Company_HashMap_Mapper81618898361876$0.java:17)
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:77)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:671)
	... 2 more
````
code is as follows:
````java
public class Company {
    private Long id;
    private String companyOID;
}   
````
````java
MapperFactory mapperFactory = new DefaultMapperFactory.Builder().useBuiltinConverters(true).build();
MapperFacade mapper = mapperFactory.getMapperFacade();
        
Map<String, Object> map = new HashMap<>();
map.put("id", Integer.valueOf(1));
map.put("companyOID",1);
Company com = mapper.map(map, Company.class);
````

The code generated automatically is as follows,as you can see, implicit conversion is used
````java
destination.setId(((java.lang.Long) ((java.lang.Object) source
				.get("id"))));
````
So, is it a defect, can it automatically identify the type, and can use the built-in converter.

**Comment by ayonel** [comment]
I caught with the same problem, hope fix

**Comment by ayonel** [comment]
> I caught with the same problem, hope fix

I fixed this using custom mapper and limit the scope by overide the `canConvert` function.

`public class ObjectToDateConverter extends CustomConverter<Object, Date> {
        @Override
        public Date convert(Object source, Type<? extends Date> destinationType, MappingContext context) {
            if (source instanceof Date) {
                return (Date) source;
            } else if (source instanceof Long) {
                return new Date((long) source);
            } else if (source instanceof String) {
                //TODO: more formatter
                try {
                    return new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).parse((String) source);
                } catch (ParseException e) {
                    return null;
                }
            } else {
                return null;
            }
        }

        /**
         * 参考：https://stackoverflow.com/questions/29615401/how-to-map-generics-objects-with-orika
         * 如果目标类是Date
         * 且源类是 String 或者 Long 或者Date
         */
        @Override
        public boolean canConvert(Type<?> sourceType, Type<?> destinationType) {
            return destinationType.getRawType().equals(Date.class) && (
                    sourceType.getRawType().equals(Date.class)
                            || sourceType.getRawType().equals(String.class)
                            || sourceType.getRawType().equals(Object.class)
                            || Long.class.isAssignableFrom(sourceType.getRawType())
            );
        }
    }`
