### ISSUE TITLE
BeanCreationException: DataMapper due to StackOverflowError

### ISSUE THREAD

**Issue by VyacheslavVolkov** [orika-mapper/orika#307]
Our configuration is:

```
<alias alias="dataMapper" name="defaultDataMapper"/>
	<bean id="defaultDataMapper" class="de.hybris.platform.webservicescommons.mapping.impl.DefaultDataMapper">
		<property name="fieldSetBuilder" ref="fieldSetBuilder"/>
	</bean>

	<alias alias="fieldSetBuilder" name="defaultFieldSetBuilder"/>
	<bean id="defaultFieldSetBuilder"
	      class="de.hybris.platform.webservicescommons.mapping.impl.DefaultFieldSetBuilder">
		<property name="defaultRecurrencyLevel" value="4"/>
		<property name="defaultMaxFieldSetSize" value="50000"/>
		<property name="fieldSetLevelHelper" ref="fieldSetLevelHelper"/>
	</bean>

	<alias alias="fieldSetLevelHelper" name="defaultFieldSetLevelHelper"/>
	<bean id="defaultFieldSetLevelHelper"
	      class="de.hybris.platform.webservicescommons.mapping.impl.DefaultFieldSetLevelHelper">
	</bean>

<!-- The rest of configuration is omitted  -->
```

Stacktrace is:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultDataMapper' defined in ServletContext resource [/WEB-INF/config/v2/dto-mappings-v2-spring.xml]: Initialization of bean failed; nested exception is java.lang.StackOverflowError
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:522)
 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:496)
 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:627)
 	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:169)
 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:318)
 	... 25 more
 Caused by: java.lang.StackOverflowError
 	at ma.glasnost.orika.metadata.Type.isAssignableFrom(Type.java:325)
 	at ma.glasnost.orika.impl.DefaultMapperFactory.getRegisteredMapper(DefaultMapperFactory.java:811)
 	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:702)
 	at ma.glasnost.orika.impl.DefaultMapperFactory.collectUsedMappers(DefaultMapperFactory.java:1445)
 	at ma.glasnost.orika.impl.DefaultMapperFactory.collectUsedMappers(DefaultMapperFactory.java:1468)
 	at ma.glasnost.orika.impl.DefaultMapperFactory.collectUsedMappers(DefaultMapperFactory.java:1468)

```

It's not reproducible for us each time we are trying to build spring context. But we don't see any specific circumstances.

**Comment by timofey** [comment]
bump, I am having the exact same issue

**Comment by stapetro** [comment]
Can you please write a test that reproduces the issue ?

**Comment by ankush12345** [comment]
Having the same issue , please help if someone find the root cause

**Comment by timofey** [comment]
Have an update that can maybe give a hint on what's going on.
@stapetro it doesn't reproduce every time, but what I've found is that in our project we had the same module deployed two times in Tomcat. So basically we had two contexts in different hosts, and the contexts contained the same .war file. When I removed the duplicate, the problem disappeared and I haven't seen it so far. So I think it has to do something with concurrency, maybe there is some bug in class cache that causes this issue
