### ISSUE TITLE
not support jdk17？

### ISSUE THREAD

**Issue by a364176773** [orika-mapper/orika#395]
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @396f6598
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at ma.glasnost.orika.converter.builtin.CloneableConverter.<init>(CloneableConverter.java:64)
	at ma.glasnost.orika.converter.builtin.CloneableConverter$Builtin.<init>(CloneableConverter.java:221)
	at ma.glasnost.orika.converter.builtin.BuiltinConverters.register(BuiltinConverters.java:135)
	at ma.glasnost.orika.impl.DefaultMapperFactory.build(DefaultMapperFactory.java:1278)
	at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:881)

Process finished with exit code 1

```

**Comment by a19930905a** [comment]
Hi @a364176773  , Sadly same issue was open in 2021 and Orika hasn't response for that
u can see there is workaround in that discussion , #377

**Comment by numacanedo** [comment]
@a364176773 There is a work around:
- Just add this jvm args, here is the code if you are using gradle
`bootRun {
    jvmArgs = ["--add-opens=java.base/java.lang=ALL-UNNAMED"]
}`

**Comment by a364176773** [comment]
Sorry, I think this method is only a temporary solution, not a real support for jdk17

**Comment by thiagolvlsantos** [comment]
I agree @a364176773! 

Looks like the authors gave up Orika, unfortunately. 

Looking to replacements already, no new projects with Orika from now on.

**Comment by Chr3is** [comment]
@thiagolvlsantos we managed to replace Orika with https://mapstruct.org/ successfully. It was straight forward but that depends on the complexity of your mappings.

**Comment by wenjiezhang2013** [comment]
duplicate of https://github.com/orika-mapper/orika/issues/377

**Comment by KaseiHaku** [comment]
@Chr3is mapstruct is too cumbersome and requires defining conversion classes for each pair of POJOs

**Comment by ToryZhou** [comment]
When using .parallelStream(),  the orika maper is not working

ma.glasnost.orika.MappingException: ma.glasnost.orika.MappingException: While attempting the following mapping:
Error occurred: java.lang.ClassCastException:

**Comment by ToryZhou** [comment]
> @thiagolvlsantos we managed to replace Orika with https://mapstruct.org/ successfully. It was straight forward but that depends on the complexity of your mappings.

MapStruct always requires the writing of mappers.

**Comment by vincentnull** [comment]
I have solved this problem. If you don't mind, you can use my jar.

https://github.com/vincentnull/orika
