### ISSUE TITLE
Deadlock with Orika 1.4.4

### ISSUE THREAD

**Issue by andresviedma** [orika-mapper/orika#56]
I've had a deadlock using Orika 1.4.4 when getting a MapperFacade from a DefaultMapperFactory. This is the deadlock threads dump:

```
"Thread-18":
    at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:721)
    - waiting to lock <0x00000007a7b3f708> (a ma.glasnost.orika.impl.MapperFacadeImpl)
    at ma.glasnost.orika.impl.DefaultBoundMapperFacade.<init>(DefaultBoundMapperFacade.java:77)
    at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:1316)
    at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:1301)
    at ma.glasnost.orika.impl.generator.UsedMapperFacadesContext.getIndex(UsedMapperFacadesContext.java:72)
    at ma.glasnost.orika.impl.generator.SourceCodeContext.usedMapperFacadeCall(SourceCodeContext.java:308)
    at ma.glasnost.orika.impl.generator.SourceCodeContext.callMapper(SourceCodeContext.java:331)
    at ma.glasnost.orika.impl.generator.SourceCodeContext.callMapper(SourceCodeContext.java:349)
    at ma.glasnost.orika.impl.generator.specification.ObjectToObject.generateMappingCode(ObjectToObject.java:44)
    at ma.glasnost.orika.impl.generator.SourceCodeContext.mapFields(SourceCodeContext.java:762)
    at ma.glasnost.orika.impl.generator.MapperGenerator.generateFieldMapCode(MapperGenerator.java:249)
    at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:172)
    at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:70)
    at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1190)
    at ma.glasnost.orika.impl.DefaultMapperFactory.build(DefaultMapperFactory.java:1049)
    - locked <0x00000007a5d99028> (a ma.glasnost.orika.impl.DefaultMapperFactory)
    at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:1313)
    at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:1301)
    at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:1326)
    at com.tuenti.platform.scheduler.quartz.config.CronJobConfigurator.getJobParams(CronJobConfigurator.java:170)
    at com.tuenti.platform.scheduler.quartz.config.CronJobConfigurator.createQuartzJob(CronJobConfigurator.java:116)
    at com.tuenti.platform.scheduler.quartz.config.CronJobConfigurator.reconfigure(CronJobConfigurator.java:68)
    at com.tuenti.platform.scheduler.quartz.config.SynchronizedQuartzConfigurator.reconfigure(SynchronizedQuartzConfigurator.java:66)
    at com.tuenti.platform.scheduler.quartz.ConfigChecker.reconfigure(ConfigChecker.java:67)
    at com.tuenti.platform.scheduler.quartz.ConfigChecker.run(ConfigChecker.java:56)
"localhost-startStop-1":
    at ma.glasnost.orika.impl.DefaultMapperFactory.build(DefaultMapperFactory.java:1035)
    - waiting to lock <0x00000007a5d99028> (a ma.glasnost.orika.impl.DefaultMapperFactory)
    at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:722)
    - locked <0x00000007a7b3f708> (a ma.glasnost.orika.impl.MapperFacadeImpl)
    at com.tuenti.platform.di.OrikaModule.provideMapperFacade(OrikaModule.java:37)
    at com.tuenti.platform.di.OrikaModule$$FastClassByGuice$$523b1b18.invoke(<generated>)
    at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:229)
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:147)
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:279)
    at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:279)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1065)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
    at com.google.inject.Scopes$1$1.get(Scopes.java:59)
    - locked <0x00000007a5f50728> (a com.google.inject.Scopes$1$1)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
    at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1008)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058)
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1004)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1039)
    at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:117)
    at com.google.inject.servlet.AbstractServletPipeline.init(AbstractServletPipeline.java:52)
    at com.google.inject.servlet.AbstractFilterPipeline.initPipeline(AbstractFilterPipeline.java:79)
    - locked <0x00000007a6208748> (a com.google.inject.servlet.ManagedFilterPipeline)
    at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:220)
    at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:277)
    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:258)
    at org.apache.catalina.core.ApplicationFilterConfig.setFilterDef(ApplicationFilterConfig.java:382)
    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:103)
    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4649)
    - locked <0x00000007a5c17480> (a java.util.HashMap)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5305)
    - locked <0x00000007a591e718> (a org.apache.catalina.core.StandardContext)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    - locked <0x00000007a591e718> (a org.apache.catalina.core.StandardContext)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:963)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1600)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

Found 1 deadlock.
```

**Comment by elaatifi** [comment]
Did you tried with version 1.4.5 ?

**Comment by andresviedma** [comment]
It's an uncommon error with a race condition, I'm not able to reproduce it so I can't know if it also happens with 1.4.5 or not. Looking at the code in 1.4.5 my impression was that the basic code of that part hadn't been changed. Do you think it could be already fixed in 1.4.5?

**Comment by elaatifi** [comment]
Yes, you're right thank you for the threadump !
This is related to https://github.com/orika-mapper/orika/blob/master/core/src/main/java/ma/glasnost/orika/impl/DefaultMapperFactory.java#L1501
The lines from 1501 to 1503 should be deleted.

The issue has been fixed for getMapperFacade but not for getMapperFacade(Type<S> sourceType, Type<D> destinationType, boolean containsCycles)

Need to do more test, one more time again thank you :)

**Comment by cnico** [comment]
Hello, 

We encounter this problem of deadlock with orika 1.4.5 in our application in production when there is a concurrent initialisation of orika by 2 web requests.

We are correcting it by calling getMapperFacade just before getMapperFacade(Type sourceType, Type destinationType, boolean containsCycles).

Do you think this point will be corrected soon ?

Regards,

**Comment by elaatifi** [comment]
It's should be fixed in 1.5.0 release

**Comment by ignacioburon** [comment]
Hello,

We have also this problem of deadlock with orika 1.4.2 in our production application, similar problem as cnico.

We have adopted the same solution of calling getMapperFacade just before the other call. It seems to work but we have no real data to certificate it yet, the issue is new. We think it has become a problem as our application has growth in usage, and the probability of concurrent web request is now more likely.

We also have a new version of the application that uses Orika quite heavily, but we have not updated it with the discussed patch, we are waiting to see if the patch corrects the issue in production.

Is there any ETA on the 1.5.0 release? I´ve been looking at the code of the actual 1.5.0 beta, and the problematic code is the same.

Thank you very much

**Comment by deba70** [comment]
So which version has this fix?
 In my application, we are seeing the racing thread condition.   Here is the call stack. I am using 1.4.6




4XESTACKTRACE                at java/util/WeakHashMap.get(WeakHashMap.java:529(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/metadata/TypeKey.getTypeIndex(TypeKey.java:37(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/metadata/TypeKey.valueOf(TypeKey.java:79(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/metadata/TypeFactory.intern(TypeFactory.java:80(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/metadata/TypeFactory.valueOf(TypeFactory.java:143(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/metadata/TypeFactory.valueOf(TypeFactory.java:348(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/CustomConverter.<init>(CustomConverter.java:49(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/converter/builtin/BuiltinBidirectionalConverter.<init>(BuiltinBidirectionalConverter.java:36(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/converter/builtin/BuiltinConverters.register(BuiltinConverters.java:127)
4XESTACKTRACE                at ma/glasnost/orika/impl/DefaultMapperFactory.build(DefaultMapperFactory.java:1185(Compiled Code))
5XESTACKTRACE                   (entered lock: ma/glasnost/orika/impl/DefaultMapperFactory@0x00000000B384A090, entry count: 1)
4XESTACKTRACE                at ma/glasnost/orika/impl/DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:1502(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/impl/DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:1490(Compiled Code))
4XESTACKTRACE                at ma/glasnost/orika/impl/DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:1516)

**Comment by andreabertagnolli** [comment]
Try with 1.5.0 or 1.5.1

**Comment by deba70** [comment]
Is it fixed in 1.5.0?

**Comment by andreabertagnolli** [comment]
You have to try it, because it's not easy to reproduce.

**Comment by taichiw** [comment]
I had same lock issue again, on 1.5.1

It looks... this thread made lock

"ajp-nio-18009-exec-11" #184 daemon prio=5 os_prio=0 tid=0x00007f1504001800 nid=0x8256 runnable [0x00007f14eaff5000]
   java.lang.Thread.State: RUNNABLE
	at java.util.WeakHashMap.get(WeakHashMap.java:403)
	at ma.glasnost.orika.metadata.TypeKey.getTypeIndex(TypeKey.java:55)
	at ma.glasnost.orika.metadata.TypeKey.valueOf(TypeKey.java:47)
	at ma.glasnost.orika.metadata.TypeFactory.intern(TypeFactory.java:437)
	at ma.glasnost.orika.metadata.TypeFactory.valueOf(TypeFactory.java:69)
	at ma.glasnost.orika.property.PropertyResolver.resolvePropertyType(PropertyResolver.java:340)
	at ma.glasnost.orika.property.PropertyResolver.processProperty(PropertyResolver.java:265)
	at ma.glasnost.orika.property.IntrospectorPropertyResolver.collectProperties(IntrospectorPropertyResolver.java:105)
	at ma.glasnost.orika.property.PropertyResolver.getProperties(PropertyResolver.java:128)
	- locked <0x00000003c7c9f7c8> (a ma.glasnost.orika.metadata.Type)
	at ma.glasnost.orika.metadata.ClassMapBuilder.<init>(ClassMapBuilder.java:123)
	at ma.glasnost.orika.metadata.ClassMapBuilder$Factory.newClassMapBuilder(ClassMapBuilder.java:70)
	at ma.glasnost.orika.metadata.ClassMapBuilderFactory.getNewClassMapBuilder(ClassMapBuilderFactory.java:142)
	- locked <0x00000003c2ace720> (a ma.glasnost.orika.metadata.ClassMapBuilder$Factory)
	at ma.glasnost.orika.metadata.ClassMapBuilderFactory.map(ClassMapBuilderFactory.java:153)
	at ma.glasnost.orika.impl.DefaultMapperFactory.classMap(DefaultMapperFactory.java:1564)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:733)
	- locked <0x00000003c19fffc8> (a ma.glasnost.orika.impl.DefaultMapperFactory)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:567)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:179)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapElement(MapperFacadeImpl.java:790)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:621)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsList(MapperFacadeImpl.java:427)

and other threads are blocked.

"ajp-nio-18009-exec-12" #242 daemon prio=5 os_prio=0 tid=0x00007f1504007800 nid=0x86e5 waiting for monitor entry [0x00007f14eb9fb000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:708)
	- waiting to lock <0x00000003c19fffc8> (a ma.glasnost.orika.impl.DefaultMapperFactory)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:567)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:179)


It looks similar with above comment by Mr. / Ms. deba70,
the locking thread is on the WeakHashMap.

**Comment by DinkarKolhe** [comment]
We are seeing this issue with 1.4.6 too. will try updating the orika version.

**Comment by juexin** [comment]
I am seeing this issue with 1.5.2 too. 

the thread dump:

"http-nio-8080-exec-298" #5198 daemon prio=5 os_prio=0 tid=0x00007fc5d40ba800 nid=0x154a waiting on condition  [0x00007fc55bbf7000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@10.0.1/Native Method)
	- parking to wait for  <0x0000000745b20518> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@10.0.1/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@10.0.1/AbstractQueuedSynchronizer.java:883)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(java.base@10.0.1/AbstractQueuedSynchronizer.java:1007)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@10.0.1/AbstractQueuedSynchronizer.java:1322)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@10.0.1/ReentrantReadWriteLock.java:738)
	at ma.glasnost.orika.util.SortedCollection.iterator(SortedCollection.java:177)
	at ma.glasnost.orika.impl.DefaultMapperFactory.getRegisteredMapper(DefaultMapperFactory.java:805)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:702)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:567)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:179)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapElement(MapperFacadeImpl.java:791)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:621)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsSet(MapperFacadeImpl.java:413)
	at ma.glasnost.orika.generated.Orika_SigningInfo_Identity_Mapper4916422670605452$4.mapAtoB(Orika_SigningInfo_Identity_Mapper4916422670605452$4.java)
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:77)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:254)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapElement(MapperFacadeImpl.java:798)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:621)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsList(MapperFacadeImpl.java:419)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsList(MapperFacadeImpl.java:706)
