### ISSUE TITLE
Error when base interface has methods with default implementations

### ISSUE THREAD

**Issue by sergey-ostapenko** [orika-mapper/orika#84]
Hi. 
When I trying to perform mapping in following test:
```java
public interface BaseA {

 default String getId() {
 return "test";
 }

 default void setId(String val) {
 }
}

public class A implements BaseA {
}

public class B {
 @Getter
 @Setter
 String id;
}

@Test
public void defaultInterfaceImplementationsTest() {
 val mapperFactory = new DefaultMapperFactory.Builder().build();

 mapperFactory.classMap(A.class, B.class)
 .byDefault()
 .register();

 A a = new A();
 B b = new B();

 mapperFactory.getMapperFacade().map(a, b);
 assertThat(b, notNullValue());
}
```

I'm getting strange compilation error:
```Caused by: compile error: getId() not found in test.unit.views.BaseViewTest$A
    at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:723)
    at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:688)
    at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)```

I tried to compile generated class by hands, and all seems to be ok...
This test looks a little bit synthetic, but real situation is exactly the same.
Any ideas on how I this error can be fixed?

**UPD** maybe `JavassistCompilerStrategy` don't support java 1.8 by default ?

**Comment by sergey-ostapenko** [comment]
Issue was really connected with old version of `javassist` dependency used in project. Latest 3.20.0-GA version solved the problem.
