### ISSUE TITLE
 Linkage problem when orika and the domain model are in different classloaders

### ISSUE THREAD

**Issue by topdeskarjens** [orika-mapper/orika#86]
In a scenario where the Orika classes and the mapped classes are loaded by different classloaders, it is possible to create the mapper, but have it fail during linkage.

Consider the following class.

        package example;

        import ma.glasnost.orika.*;
        import ma.glasnost.orika.impl.*;

        public class Example {
                public static class A { }
                public static class B { }

                public static void main(String... args) {
                        MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
                        mapperFactory.classMap(A.class, B.class).register();
                        BoundMapperFacade<A, B> facade = mapperFactory.getMapperFacade(A.class, B.class);
                        facade.map(new A());
                }
        }

Running it (with Orika + dependencies on the classpath) produces no runtime errors.

Now package the compiled Example classes in an `example.jar` and load them with the following runner:

        import java.net.URLClassLoader;
        import java.io.File;
        import java.net.URL;
        import java.lang.reflect.*;

        public class Runner {
                public static void main(String... args) throws Exception {
                        URLClassLoader cl = new URLClassLoader(new URL[] {new File("example.jar").toURL()}, Runner.class.getClassLoader());
                        Thread.currentThread().setContextClassLoader(cl);

                        Class<?> example = cl.loadClass("example.Example");
                        Method main = example.getMethod("main", args.getClass());
                        main.invoke(null, new Object[] { args });
                }
        }

Executing Runner in a classpath containing Orika + dependencies results in a runtime failure.

        Exception in thread "main" java.lang.reflect.InvocationTargetException
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:497)
                at Runner.main(Runner.java:13)
        Caused by: java.lang.NoClassDefFoundError: example/Example$A
                at ma.glasnost.orika.generated.Orika_B_A_Mapper1965230208308$0.mapAtoB(Orika_B_A_Mapper1965230208308$0.java)
                at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:67)
                at ma.glasnost.orika.impl.DefaultBoundMapperFacade.map(DefaultBoundMapperFacade.java:137)
                at ma.glasnost.orika.impl.DefaultBoundMapperFacade.map(DefaultBoundMapperFacade.java:94)
                at example.Example.main(Example.java:14)
                ... 5 more
        Caused by: java.lang.ClassNotFoundException: example.Example$A
                at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                ... 10 more

This scenario is an extreme simplification of the case where Orika is on the classpath of a (web/ee) container and the domain model is inside a WAR file.

This behaviour is related to the classloader that is used to load the generated classfile. This choice is made near the end of `JavassistCompilerStrategy` in the call to `byteCodeClass.toClass`. It currently uses the classloader that loaded that class. Given the context classloader is considered during the compilation of the generated class, it seems reasonable to us to also use it when loading the generated class. I can confirm that making such a change fixes both this simplified example and our real-world use case.

**Comment by andreabertagnolli** [comment]
I tried to replicate this with simplification showed in the first post, but i can't replicate the exception, it works.

There's a possibility to replicate it? or can we consider this closed?

**Comment by brabenetz** [comment]
sounds similar to #62
Maybe the solution from @Jtalk works:
"The simple workaround is to subclass JavassistCompilerStrategy in your deployment so it's class is loaded by deployment CL. Your overridden class should then be manually applied to the Orika MapperFactory (new DefaultMapperFactory.Builder().compilerStrategy(new YourSubclass()).build() should do the trick)."

**Comment by tsoroka** [comment]
This issue still reproducible with Tomcat 9.0.17 and Java version > 8. With Java version 8 issue is not reproducible. Orika version 1.5.4. Subclassing of JavassistCompilerStrategy did not help.

`Caused by: java.lang.ClassNotFoundException: ma.glasnost.orika.impl.GeneratedMapperBase
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor59.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at javassist.ClassPool.toClass2(ClassPool.java:1183) ~[javassist-3.21.0-GA.jar:?]
	at javassist.ClassPool.toClass(ClassPool.java:1164) ~[javassist-3.21.0-GA.jar:?]
	at javassist.CtClass.toClass(CtClass.java:1316) ~[javassist-3.21.0-GA.jar:?]
	at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.compileClass(JavassistCompilerStrategy.java:246) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.generator.SourceCodeContext.compileClass(SourceCodeContext.java:228) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.generator.SourceCodeContext.getInstance(SourceCodeContext.java:244) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:73) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1478) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:738) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:568) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:178) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapElement(MapperFacadeImpl.java:792) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:622) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsList(MapperFacadeImpl.java:428) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.generated.Orika_FlightOfferPassengerContextSearchTO_FlightOfferPassengerContextSearch_Mapper341361519670733$38.mapAtoB(Orika_FlightOfferPassengerContextSearchTO_FlightOfferPassengerContextSearch_Mapper341361519670733$38.java) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:77) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:253) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapElement(MapperFacadeImpl.java:799) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:622) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsList(MapperFacadeImpl.java:428) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.generated.Orika_CheckOfferSearchTO_CheckOfferSearch_Mapper341361496484122$35.mapAtoB(Orika_CheckOfferSearchTO_CheckOfferSearch_Mapper341361496484122$35.java) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:77) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.DefaultBoundMapperFacade.map(DefaultBoundMapperFacade.java:137) ~[orika-core-1.5.4.jar:?]
	at ma.glasnost.orika.impl.DefaultBoundMapperFacade.map(DefaultBoundMapperFacade.java:94) ~[orika-core-1.5.4.jar:?]
`

**Comment by tsoroka** [comment]
Could be fixed as described in https://stackoverflow.com/questions/52321672/orika-wrong-classloader-used-in-case-of-using-embedded-tomcat
