### ISSUE TITLE
Mapping between Map<a, Map<b, c>> causes null pointer exception

### ISSUE THREAD

**Issue by axper** [orika-mapper/orika#98]
Using orika 1.4.6

    public class Class1 {
        private Map<String, Map<Integer, Integer>> a;
        ...
    }

    public class Class2 {
        private Map<String, Map<Integer, Integer>> a;
        ...
    }

    mapperFactory.classMap(Class1.class, Class2.class).byDefault().register();
    
The code above produces an exception like this:
```
Caused by: ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceType = Class1
sourceProperty = a(Map<String, Map>)
destinationType = Class2
destinationProperty = a(Map<String, Map>)
Error occurred: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:177)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:72)
	... 65 more
Caused by: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.VariableRef.isPrimitive(VariableRef.java:138)
	at ma.glasnost.orika.impl.generator.VariableRef.<init>(VariableRef.java:78)
	at ma.glasnost.orika.impl.generator.specification.MapToMap.generateMappingCode(MapToMap.java:72)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.mapFields(SourceCodeContext.java:768)
	at ma.glasnost.orika.impl.generator.specification.MapToMap.generateMappingCode(MapToMap.java:81)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.mapFields(SourceCodeContext.java:768)
	at ma.glasnost.orika.impl.generator.MapperGenerator.generateFieldMapCode(MapperGenerator.java:251)
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:174)
	... 66 more
```

**Comment by andreabertagnolli** [comment]
Duplicated of #67 , which is resolved now

**Comment by andreabertagnolli** [comment]
@elaatifi can you close it?
